weight = 1
# language code
languageCode = "en"
# language name
languageName = "English"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = true
# copyright description used only for seo schema
copyright = "This website is protected under full copyright. All rights reserved. However, individual blog posts are available under a Creative Commons Attribution-NonCommercial 4.0 International License unless otherwise stated."
