name: CI

on:
  push: {}

jobs:
  compare-multilingual-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make the script executable
        run: chmod +x scripts/compare-multi-lang-posts.sh

      - name: Run Compare Script
        id: compare
        run: |
          OUTPUT=$(./scripts/compare-multi-lang-posts.sh)
          echo "$OUTPUT"
          echo "result=$OUTPUT" >> $GITHUB_ENV

      - name: Verify Script Output
        run: |
          if [[ "$result" != *"0 different"* ]]; then
            echo "Error: Script output does not contain '0 different'."
            exit 1
          fi
        env:
          result: ${{ env.result }}

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v20
      with:
        globs: |
          **/*.md
